# Generated by Django 5.0.7 on 2024-08-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chore', '0002_chore_frequency'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='chore',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AddField(
            model_name='chore',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='room',
            name='slug',
            field=models.SlugField(default=''),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
