name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main  # or any other branch you want to trigger deployment from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "$ACTIONS_DEPLOY_KEY" | tr -d '\r' | ssh-add -
          echo "$SERVER_SSH_KEY" >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SSH_AUTH_SOCK: /tmp/ssh-agent.sock
        run: |
          # Sync the updated code with the server
          rsync -avz --delete-after --exclude '.git' --exclude '__pycache__' . root@:161.35.204.244/webapps/chores-tracker/

          # SSH into server and run the restart script
          ssh root@161.35.204.244 'cd /webapps/chores-tracker && ./restart.sh'

